### ISSUE TITLE
evaluation

### ISSUE THREAD

**Issue by shashanka300** [zackhy/TextClassification#1]
training works fine how to evaluate the trained model

**Comment by sskrishn** [comment]
same question! How to evaluate the trained model ?

**Comment by zackhy** [comment]
@sskrishn @shashanka300 Hey guys, sorry for the late response. I estimate the models' performance according to their accuracy on the validation set. You can check the Tensorboard summaries for the accuracy curves. Please see train.py.

**Comment by purohitvivek8** [comment]
@zackhy How we can test with sample data after train?

**Comment by purohitvivek8** [comment]
and please update license version

**Comment by zackhy** [comment]
@purohitvivek8 I will add a test.py for loading the trained model for test this week.

**Comment by purohitvivek8** [comment]
OK Thanks @zackhy and please add license version so we can use in our existing code

**Comment by zackhy** [comment]
@purohitvivek8 test.py and license added

**Comment by purohitvivek8** [comment]
Thank you so much @zackhy
