### ISSUE TITLE
你好，请问如何预测单个句子？

### ISSUE THREAD

**Issue by albertyou2** [zackhy/TextClassification#6]
@zackhy 作者您好：
     很易用的库。我几分钟就用起来了，同时用的是自己的数据，目前准确率也不错！！赞一个
     但是您的 test.py是一个测试一组数据并给出准确率的方法。
     请问如何写一个最小的预测的python脚本？
     例如 ： python predict.py  '需要预测分类的句子'    ，输出是 分类标签例如 ： 2
     刚刚接触tensorflow不久，望您指导下，谢谢！

**Comment by zackhy** [comment]
@albertyou2 把batch_size设为1即可

**Comment by albertyou2** [comment]
@zackhy 谢谢，另外我好像没看到在哪里设置学习率的衰减策略？

**Comment by zackhy** [comment]
@albertyou2 是的，我没有用learning rate decay。

**Comment by albertyou2** [comment]
@zackhy 请问有没有方法可以简单的加入一个 衰减的 方法？ 我发现目前训练到72% 上不去了，怀疑是学习率的原因，谢谢您

**Comment by zackhy** [comment]
@albertyou2 这个网上教程挺多的，你可以google一下，设一个decay rate，然后每几轮decay一次，改一下train.py就可以了。我过几天有空的话可能会把这个加进去~

**Comment by albertyou2** [comment]
好的谢谢您！

**Comment by zackhy** [comment]
@albertyou2 加了learning rate decay
