### ISSUE TITLE
Tensorflow1.5以上不支持 FLAGS.__flags

### ISSUE THREAD

**Issue by woohaoshu** [zackhy/TextClassification#7]
https://github.com/zackhy/TextClassification/blob/d893212f72ab59b51a4e3cff76ee5f460ca322c7/train.py#L90
tf1.5以上版本应该改为：
`params = FLAGS.flag_values_dict()`
参考https://stackoverflow.com/questions/40286298/how-to-access-all-flags-and-get-their-values-using-loop-in-tensorflow/48748404#48748404

**Comment by woohaoshu** [comment]
FLAGS.__flags未修改的结果如下：
`Parameters:
batch_size: <absl.flags._flag.Flag object at 0x000001144608C8D0>
...`

**Comment by zackhy** [comment]
@woohaoshu 好的，感谢！
