### ISSUE TITLE
Train/test examples in README.md

### ISSUE THREAD

**Issue by ducalpha** [zackhy/TextClassification#8]
Both the training and testing command examples in README.md use the same `./data/data.csv`. It seems misleading for me because the train data should be different from the test data.
How about using 2 different csv files:
`python train.py --data_file=./data/data.train.csv`
and
`python test.py --test_data_file=./data/data.test.csv`

**Comment by zackhy** [comment]
@ducalpha Sure. Thanks for the advice.
